### ISSUE TITLE
node 版本是多少啊

### ISSUE THREAD

**Issue by hejun041** [CenBoMin/JDTASK_V2P#1]
任务执行报
`安装检查, 失败! 原因: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/app/node_modules/got/dist/source/index.js
require() of ES modules is not supported.
require() of /usr/local/app/node_modules/got/dist/source/index.js from /usr/local/app/script/runJSFile.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/app/node_modules/got/package.json.`

还有就是

[JDTask...js info][2021-07-23 23:36:45.233] ./inti.sh finished
[JDTas...js error][2021-07-23 23:36:45.231] ./inti.sh: Permission denied
[JDTas...js error][2021-07-23 23:36:45.230] /bin/sh:
[JDTask...js info][2021-07-23 23:36:45.228] start run command: ./inti.sh cwd: script/JSFile

权限问题

姐姐看有什么指导没有

**Comment by hejun041** [comment]
我的node版本是v8.10.0

**Comment by hejun041** [comment]
> @hejun041 我的也是这样，google了下说是node js版本太高，脚本的语法没更新上来。。

你这个回复的也太快了吧😄

**Comment by hejun041** [comment]
还有就是手动拉取代码
`[JDTas...js error][2021-07-23 23:46:58.550] fatal: not in a git directory
[JDTas...js error][2021-07-23 23:46:58.549] fatal: not in a git directory
[JDTas...js error][2021-07-23 23:46:58.548] fatal: not in a git directory
[JDTask...js info][2021-07-23 23:46:58.546] start run command: git config pull.rebase false && git fetch https://ghproxy.com/https://github.com/Aaron-lv/sync && git pull origin jd_scripts:Aaron && git log --pretty=format:"%h - %an, %ar : %s" --since=2.day cwd: script/JSFile/sync
[JDTask...js info][2021-07-23 23:46:58.542] start run command: git config pull.rebase false && git fetch https://ghproxy.com/https://github.com/JDHelloWorld/jd_scripts && git pull origin main:JDHelloWorld && git log --pretty=format:"%h - %an, %ar : %s" --since=2.day cwd: script/Shell`

`fatal: not in a git directory`

手动git clone 倒是可以拉下来

**Comment by LevineWoo** [comment]
@hejun041 我的之前有这个问题，但是后来换成host网络模式后就不会了。
